# This is a basic workflow to help you get started with Actions

name: GitHub Actions Build and Deploy Doc

# Controls when the workflow will run
on:
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Deploy 🚀
        uses: jenkey2011/vuepress-deploy@c125854a55a2d3fbe1847e0fc25a4aa662582520
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: tuia-fed/tuia-animation-less
          TARGET_BRANCH: gh-pages
          BUILD_SCRIPT: yarn install yarn build && node plugins/fs-copy && yarn docs:build
          BUILD_DIR: docs/dost
